### ISSUE TITLE
crash when adding image from gallery

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#107]
1. Add a new product.
2. See details
3. Edit
4. Add a new photo from the gallery

=> A crash is reported, and the app returns to the product list screen. No photo is added.

Tested on deployed Play Store app, Moto G3 / 5.1

**Comment by ptyagicodecamp** [comment]
I'm guessing that following error log could be the reason behind the missing uploaded picture. Its interesting that not all photos have this problem. This issue needs a deeper evaluation.

07-15 23:56:42.604 1452-3006/? E/Parcel: Class not found when unmarshalling: com.mtesitoo.backend.model.Product
                                         java.lang.ClassNotFoundException: com.mtesitoo.backend.model.Product
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                             at android.os.Parcel.readParcelable(Parcel.java:2358)
                                             at android.os.Parcel.readValue(Parcel.java:2264)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:920)
                                             at android.content.Intent.getStringExtra(Intent.java:6183)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2707)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2169)
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6338)
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6116)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3986)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.mtesitoo.backend.model.Product
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                             at android.os.Parcel.readValue(Parcel.java:2264) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                             at android.content.Intent.getStringExtra(Intent.java:6183) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2707) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2169) 
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6338) 
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6116) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3986) 
                                             at android.os.Binder.execTransact(Binder.java:453) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by ptyagicodecamp** [comment]
Seems to be issue with spaces in image filename. 

@david-r-edgar : Could you confirm if your image has space in its filename.

I see following error reported in logcat:
07-16 00:02:26.734 21256-22663/? E/Volley: [72485] BasicNetwork.performRequest: Unexpected response code 400 for https://tesitoo.com/api/v1//product/product/208/image?files=2017-05-12 13.03.36_1500188120-500x500.jpg

**Comment by david-r-edgar** [comment]
Hmmm, I retested and found something different.

If when I upload from the gallery, I select ES File Explorer, or another file manager, it works fine.

But if I use the default image selection option, I see the crash every time (whether or not there are spaces anywhere in the filename / path).

So I don't know what the problem is. Maybe it's a problem with the image selection tool (which is just called 'Images' - is it an app or what?) on Moto G3. But I'm fairly sure I've used the same method for selecting image files to upload to other apps.

**Comment by ptyagicodecamp** [comment]
Do you have a crash log that I can look into.

**Comment by david-r-edgar** [comment]
Not at the moment, will look into how I can get one on my unrooted device.

**Comment by edu11** [comment]
I was able to reproduce this error and get some logs from my device (Nexus 7, running Android 6.0.1). 

08-04 14:37:15.681 2599-2599/com.tesitoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.tesitoo, PID: 2599
                                                           java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65539, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:156 flg=0x1 }} to activity {com.tesitoo/com.mtesitoo.ProductActivity}: java.lang.NullPointerException
                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                               at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                            Caused by: java.lang.NullPointerException
                                                               at java.io.File.<init>(File.java:262)
                                                               at com.mtesitoo.model.ImageFile.<init>(ImageFile.java:0)
                                                               at com.mtesitoo.fragment.ProductDetailEditFragment.onActivityResult(ProductDetailEditFragment.java:507)
                                                               at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                               at android.app.Activity.dispatchActivityResult(Activity.java:6932)
                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
                                                               at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ptyagicodecamp** [comment]
I can confirm this issue is related to API 25 due to recent changes in how image path was being extracted from content uri.

**Comment by ptyagicodecamp** [comment]
fix deployed to play store (vercode- 8).
