### ISSUE TITLE
Random crash log

### ISSUE THREAD

**Issue by ptyagicodecamp** [projectwife/mtesitoo-android#120]
Seeing this crash log when clicking to load product from Product listing:

**Comment by ptyagicodecamp** [comment]
07-15 23:56:42.604 1452-3006/? E/Parcel: Class not found when unmarshalling: com.mtesitoo.backend.model.Product
java.lang.ClassNotFoundException: com.mtesitoo.backend.model.Product
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
at android.os.Parcel.readParcelable(Parcel.java:2358)
at android.os.Parcel.readValue(Parcel.java:2264)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
at android.os.BaseBundle.unparcel(BaseBundle.java:221)
at android.os.BaseBundle.getString(BaseBundle.java:920)
at android.content.Intent.getStringExtra(Intent.java:6183)
at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2707)
at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2169)
at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6338)
at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6116)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3986)
at android.os.Binder.execTransact(Binder.java:453)
Caused by: java.lang.ClassNotFoundException: com.mtesitoo.backend.model.Product
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at java.lang.Class.classForName(Native Method) 
at java.lang.Class.forName(Class.java:324) 
at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
at android.os.Parcel.readParcelable(Parcel.java:2358) 
at android.os.Parcel.readValue(Parcel.java:2264) 
at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
at android.os.BaseBundle.getString(BaseBundle.java:920) 
at android.content.Intent.getStringExtra(Intent.java:6183) 
at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2707) 
at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2169) 
at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6338) 
at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6116) 
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170) 
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3986) 
at android.os.Binder.execTransact(Binder.java:453) 
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
