### ISSUE TITLE
Crash editing profile picture

### ISSUE THREAD

**Issue by edu11** [projectwife/mtesitoo-android#135]
Related to #107 

The app crashes after selecting picture from gallery in Profile screen.

08-04 12:07:18.706 3097-3097/com.tesitoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.tesitoo, PID: 3097
                                                           java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65539, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:137 flg=0x1 }} to activity {com.tesitoo/com.mtesitoo.ProductActivity}: java.lang.NullPointerException
                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                               at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                            Caused by: java.lang.NullPointerException
                                                               at java.io.File.<init>(File.java:262)
                                                               at com.mtesitoo.model.ImageFile.<init>(ImageFile.java:0)
                                                               at com.mtesitoo.fragment.ProductDetailEditFragment.onActivityResult(ProductDetailEditFragment.java:507)
                                                               at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                               at android.app.Activity.dispatchActivityResult(Activity.java:6932)
                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
                                                               at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ptyagicodecamp** [comment]
Fix deployed to APK version code #8
