### ISSUE TITLE
Application crashes when trying to view item details

### ISSUE THREAD

**Issue by JimPiquant** [projectwife/mtesitoo-android#26]
To reproduce, login as vendor1, then click on "View Details" for any item.

**Comment by JimPiquant** [comment]
Here is a stack dump:

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mtesitoo, PID: 2431
                  java.lang.IllegalArgumentException: Path must not be empty.
                      at com.squareup.picasso.Picasso.load(Picasso.java:297)
                      at com.daimajia.slider.library.SliderTypes.BaseSliderView.bindEventAndShow(BaseSliderView.java:213)
                      at com.daimajia.slider.library.SliderTypes.DefaultSliderView.getView(DefaultSliderView.java:25)
                      at com.daimajia.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:81)
                      at com.daimajia.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
                      at com.daimajia.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
                      at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:998)
                      at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:930)
                      at com.daimajia.slider.library.Tricks.ViewPagerEx.onMeasure(ViewPagerEx.java:1453)
                      at android.view.View.measure(View.java:17547)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                      at android.view.View.measure(View.java:17547)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                      at android.view.View.measure(View.java:17547)
                      at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1260)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                      at android.widget.ScrollView.onMeasure(ScrollView.java:337)
                      at android.view.View.measure(View.java:17547)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                      at android.view.View.measure(View.java:17547)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
                      at android.view.View.measure(View.java:17547)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
                  	at android.view.ViewRoot
I/CrashlyticsCore: Crashlytics report upload complete: 57FA803803CE-0001-097F-8E18E910DE56.cls

**Comment by JimPiquant** [comment]
Note: this might be for old items.  It seems to be working fine with a newly added item.

**Comment by david-r-edgar** [comment]
This is the same as #21
