### ISSUE TITLE
Fatal Crash in Prod - NullPointerException in RegistrationActivity

### ISSUE THREAD

**Issue by carlpoole** [projectwife/mtesitoo-android#56]
RegistrationActivity.java line 366
com.mtesitoo.RegistrationActivity.onGetPage

Samsung SM-G920F - Andriod v6.0.1

https://fabric.io/socialcoder/android/apps/com.mtesitoo/issues/5852b32d0aeb16625b06e683

```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mtesitoo/com.mtesitoo.RegistrationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.tech.freak.wizardpager.model.Page com.tech.freak.wizardpager.model.AbstractWizardModel.findByKey(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5387)
       at android.app.ActivityThread.access$1200(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.tech.freak.wizardpager.model.Page com.tech.freak.wizardpager.model.AbstractWizardModel.findByKey(java.lang.String)' on a null object reference
       at com.mtesitoo.RegistrationActivity.onGetPage(RegistrationActivity.java:366)
       at com.tech.freak.wizardpager.ui.TextFragment.onCreate(TextFragment.java:43)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:1939)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2037)
       at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:154)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:289)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:61)
       at com.mtesitoo.RegistrationActivity.onCreate(RegistrationActivity.java:231)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5387)
       at android.app.ActivityThread.access$1200(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by carlpoole** [comment]
Currently implementing new registration page which should make this issue go away since we wont be using the wizardpager. Will update when complete! Thanks

**Comment by david-r-edgar** [comment]
Not seen when using the latest released version.
