### ISSUE TITLE
Fatal Crash in Prod: Null Pointer Exception

### ISSUE THREAD

**Issue by carlpoole** [projectwife/mtesitoo-android#59]
No message returning on error response? 
Can't currently see which user is attached to the crash. Will look at adding this in future update so we can correlate to a specific user.

https://fabric.io/socialcoder/android/apps/com.mtesitoo/issues/57f4234a0aeb16625b23f4c9

```java
Fatal Exception: java.lang.NullPointerException: println needs a message
       at android.util.Log.println_native(Log.java)
       at android.util.Log.e(Log.java:334)
       at com.mtesitoo.backend.service.LoginResponse.onErrorResponse(LoginResponse.java:51)
       at com.android.volley.Request.deliverError(Request.java:590)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by ptyagicodecamp** [comment]
@gwenpowers This crash is probably happening because of null error message passed to the println method. Please add a check to handle this. Thanks !

**Comment by gwenpowers** [comment]
As per Priyanka, bug has been fixed already.

**Comment by ptyagicodecamp** [comment]
yes, it's fixed. closing it.
