### ISSUE TITLE
[Mobile] Crashing when saving a product

### ISSUE THREAD

**Issue by ptyagicodecamp** [projectwife/mtesitoo-android#71]
Crashing with following logs when clicking "Done" in "Edit" mode.

**Crash log:**

com.mtesitoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.mtesitoo, PID: 13225
                                                              java.lang.NumberFormatException: Invalid int: "Category"
                                                                  at java.lang.Integer.invalidInt(Integer.java:138)
                                                                  at java.lang.Integer.parse(Integer.java:410)
                                                                  at java.lang.Integer.parseInt(Integer.java:367)
                                                                  at java.lang.Integer.parseInt(Integer.java:334)
                                                                  at java.lang.Integer.valueOf(Integer.java:525)
                                                                  at com.mtesitoo.backend.model.Product.getCategoriesStringList(Product.java:213)
                                                                  at com.mtesitoo.fragment.ProductDetailFragment.onViewCreated(ProductDetailFragment.java:123)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                                                                  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ptyagicodecamp** [comment]
Done.
