### ISSUE TITLE
It's possible (in a broken kind of a way) to delete non-existing product images

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#94]
- I viewed a product with no images.
- Then I clicked Edit.
- Then I clicked on the placeholder image.
- The regular dialog was shown.
- I clicked "Delete this image".
- I'm told it was deleted successfully! (this must be wrong)
- Then I clicked "Delete this image" again.
- This time, I get a crash from a divide by zero exception (see the logs below)

We should simply remove or disable the "Delete this image" button (keeping just the "add image" button) when the user clicks on a placeholder image.

```
05-05 15:30:22.061 10332-10332/com.tesitoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.tesitoo, PID: 10332
                                                             java.lang.ArithmeticException: divide by zero
                                                                 at com.daimajia.slider.library.SliderLayout.getCurrentPosition(SliderLayout.java:613)
                                                                 at com.mtesitoo.fragment.ProductDetailEditFragment$2$1.onResult(ProductDetailEditFragment.java:270)
                                                                 at com.mtesitoo.fragment.ProductDetailEditFragment$2$1.onResult(ProductDetailEditFragment.java:267)
                                                                 at com.mtesitoo.backend.service.ProductImageDeleteResponse.onResponse(ProductImageDeleteResponse.java:29)
                                                                 at com.mtesitoo.backend.service.ProductImageDeleteResponse.onResponse(ProductImageDeleteResponse.java:20)
                                                                 at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
                                                                 at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
                                                                 at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ptyagicodecamp** [comment]
Fixed in https://github.com/projectwife/mtesitoo-android/pull/105

**Comment by david-r-edgar** [comment]
Verified fixed in deployed app.
